display_name: SkyStream
package_name: skystream
description: A modern, media streaming client.
maintainer:
  name: Akash
  email: akashdh11@gmail.com
priority: optional
section: utils
depends:
  - libgtk-3-0
  - liblzma5
  - libvlc5
  - vlc-plugin-base
  - libasound2
installed_size: 0
icon: ios/Runner/Assets.xcassets/AppIcon.appiconset/AppIcon~ios-marketing.png
categories:
  - Video
  - AudioVideo
  - Player
generic_name: Media Player
postinstall_scripts:
  - if [ -f /opt/skystream/skystream ]; then ln -sf /opt/skystream/skystream /usr/bin/skystream; elif [ -f /usr/share/skystream/skystream ]; then ln -sf /usr/share/skystream/skystream /usr/bin/skystream; fi
  - chmod +x /usr/bin/skystream
  - if command -v update-desktop-database > /dev/null 2>&1; then update-desktop-database -q /usr/share/applications || true; fi
postuninstall_scripts:
  - rm -f /usr/bin/skystream
  - if command -v update-desktop-database > /dev/null 2>&1; then update-desktop-database -q /usr/share/applications || true; fi
